# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme: dark
  theme_night: dark
  font: ''
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Website of a Phd Student'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''  
  verification:
    google: ''
    baidu: ''




# Contact (edit or remove options as required)

email: Raymond.zhang[atchoum]hotmail.fr
# phone: 888 888 88 88
address:
  street: 3 rue Joliot-Curie
  city: Gif-sur-Yvette
  region: Essonne
  postcode: '91190'
  country: France
  country_code: '+33'
# coordinates:
#   latitude: '37.4275'
#   longitude: '-122.1697'
directions: Batiment Bréguet
# office_hours:
#   - 'Monday 10:00 to 13:00'
#   - 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
# contact_links:
#   - icon: twitter
#     icon_pack: fab
#     name: DM Me
#     link: 'https://twitter.com/Twitter'
#   - icon: skype
#     icon_pack: fab
#     name: Skype Me
#     link: 'skype:echo123?call'
#   - icon: keybase
#     icon_pack: fab
#     name: Chat on Keybase
#     link: 'https://keybase.io/'
#   - icon: comments
#     icon_pack: fas
#     name: Discuss on Forum
#     link: 'https://discourse.gohugo.io'

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'
  address_format: en-us



# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/raymzhang/raymzhangWebSite'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: master
    local_backend: false
  academicons:
    enable: true

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

icon:
  pack:
    ai: true
